export const ROUTES = {
  USER: {
    HOME: "/",
    PRODUCT_LIST: "/products",
    PRODUCT_DETAIL: "/products/:id",
    CART_LIST: "/checkout/cart",
    CHECKOUT_INFO: "/checkout/info",
    CHECKOUT_SUCCESS: "/checkout/success",
    ABOUT: "/about",
    ABOUT_POLICY: "/about/chinh-sach",
    NEWS_1: "/new/1",
    NEWS_2: "/new/2",
    NEWS_3: "/new/3",
    NEWS_4: "/new/4",
    PROFILE: "/profile",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    PRODUCT_MANAGEMENT: "/admin/products",
    CREATE_PRODUCT: "/admin/products/create",
    UPDATE_PRODUCT: "/admin/products/:id/update",
  },
  LOGIN: "/login",
  REGISTER: "/register",
};
